y = int(4.0)
x = int(2.0)
print("two times four is...")
print(x * y)
a = int(4.0)
b = int(2.0)
print("four times two is...")
print(a * b)
c = int(8.0)
d = int(1.0)
print("eight times one is...")
print(c * d)
